name: CI for Development Environment

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '7.2'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      # run: composer install --prefer-dist --no-progress --no-suggest
      run: composer install

    - name: Install and setup NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install
    - run: npm run production
    - name: Commit built assets
      run: |
        git config --local user.email "joseph_farillas@yahoo.com"
        git config --local user.name "jfarillas"
        git checkout -b deploy
        git add -f public/
        git commit -m "Build front-end assets"
        git push -f origin deploy

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
